server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:1209/anwser
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      matching-strategy: ant_path_matcher
knife4j:
  enable: true #开启增强配置
  basic: #基本的登录认证
    enable: true
    username: admin
    password: 123456


logging:
  level:
    yqh:
      mapper: debug
      service: info
      controller: info

mybatis:
  configuration:  # setting配置
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: yqh.pojo # 配置别名
  mapper-locations: classpath:/mapper/*.xml # mapperxml位置
#spring:
#  datasource:
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:1209/anwser
#      username: root
#      password: 123456

